services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hitman
      POSTGRES_DB: helpdesk
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://postgres:hitman@db:5432/helpdesk
      BETTER_AUTH_SECRET: XbXOIDVt2a6852NACg6XEwLxIE0+xh2NdUhk1lDaUho=
      BETTER_AUTH_URL: http://localhost:3001
      GROQ_API_KEY: your-groq-api-key-here
      SENTRY_DSN: ""

volumes:
  pgdata:
