import { db } from "../src/db";

const TICKETS: Array<{
  subject: string;
  body: string;
  fromName: string;
  fromEmail: string;
  category: "GeneralQuestion" | "TechnicalQuestion" | "RefundRequest";
  status: "Open" | "Resolved" | "Closed";
  daysAgo: number;
}> = [
  // --- RefundRequest ---
  {
    subject: "Request for refund - order #10482",
    body: "Hi, I ordered the wrong size and would like a full refund. I haven't opened the package. Order placed 3 days ago.",
    fromName: "Emma Wilson",
    fromEmail: "emma.wilson@gmail.com",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 2,
  },
  {
    subject: "Double charged on my credit card",
    body: "I was charged twice for my subscription renewal this month. Please refund the duplicate charge of $49.99.",
    fromName: "James Carter",
    fromEmail: "j.carter@outlook.com",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 10,
  },
  {
    subject: "Cancelled subscription but still billed",
    body: "I cancelled my Pro plan on the 15th but was still charged on the 20th. Please issue a refund.",
    fromName: "Priya Sharma",
    fromEmail: "priya.sharma@yahoo.com",
    category: "RefundRequest",
    status: "Closed",
    daysAgo: 30,
  },
  {
    subject: "Product arrived damaged - need refund",
    body: "The item I received was cracked and unusable. Attached are photos. I'd like a full refund rather than a replacement.",
    fromName: "Liam O'Brien",
    fromEmail: "liam.obrien@hotmail.com",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 7,
  },
  {
    subject: "Accidental purchase - please refund",
    body: "My 7-year-old made an in-app purchase without my knowledge. The transaction was $29.99. Can you please reverse it?",
    fromName: "Sophie Turner",
    fromEmail: "sophie.turner@gmail.com",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 1,
  },
  {
    subject: "Service never delivered - requesting refund",
    body: "I paid for the premium onboarding session scheduled for last Thursday but no one joined the call. I want a refund.",
    fromName: "David Kim",
    fromEmail: "dkim@protonmail.com",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 5,
  },
  {
    subject: "Wrong item shipped, want refund not exchange",
    body: "You sent me Model A instead of Model B. I don't want an exchange — please just refund my $89.",
    fromName: "Aisha Patel",
    fromEmail: "aisha.patel@gmail.com",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 14,
  },
  {
    subject: "Annual plan refund request",
    body: "I signed up for the annual plan by mistake — I meant to pick monthly. Can I get a pro-rated refund for the remaining months?",
    fromName: "Noah Fernandez",
    fromEmail: "noah.fernandez@icloud.com",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 3,
  },
  {
    subject: "Charged after free trial ended early",
    body: "My free trial was supposed to last 14 days but I was charged after 7 days. Please refund the $19.99.",
    fromName: "Chloe Bennett",
    fromEmail: "chloe.b@gmail.com",
    category: "RefundRequest",
    status: "Closed",
    daysAgo: 45,
  },
  {
    subject: "Event cancelled — need full refund",
    body: "The webinar I purchased a ticket for (order #7731) was cancelled with only 2 hours notice. I'd like my $75 back.",
    fromName: "Marcus Johnson",
    fromEmail: "m.johnson@company.com",
    category: "RefundRequest",
    status: "Closed",
    daysAgo: 60,
  },
  {
    subject: "Duplicate order created by system error",
    body: "Your checkout page timed out and I clicked twice. Two identical orders were placed (IDs: 9921 and 9922). Please cancel and refund one.",
    fromName: "Isabella Moore",
    fromEmail: "isabella.m@live.com",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 8,
  },
  {
    subject: "Refund for unused team seats",
    body: "We downsized and are paying for 10 seats but only using 3. Can we get a partial refund for the 7 unused seats this quarter?",
    fromName: "Ryan Hughes",
    fromEmail: "ryan@techstartup.io",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 4,
  },
  {
    subject: "Item not as described — refund please",
    body: "The listing said 'waterproof' but the product got damaged in light rain. This is misleading advertising. I want a refund.",
    fromName: "Olivia Chen",
    fromEmail: "olivia.chen@gmail.com",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 2,
  },
  {
    subject: "Subscription downgrade credit",
    body: "I downgraded from Business to Starter mid-cycle. I expected a credit but it hasn't appeared. When will it be applied?",
    fromName: "Ethan Brooks",
    fromEmail: "ethan.brooks@yahoo.com",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 18,
  },
  {
    subject: "Unauthorized charge on my account",
    body: "I noticed a $99 charge from your company on my statement but I never signed up for anything. Please investigate and refund.",
    fromName: "Mia Robertson",
    fromEmail: "mia.rob@gmail.com",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 1,
  },
  {
    subject: "Gift card purchase failed but money deducted",
    body: "I tried to buy a $50 gift card but the transaction failed. The money still left my account. Please refund.",
    fromName: "Lucas Nguyen",
    fromEmail: "lucas.nguyen@outlook.com",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 9,
  },
  {
    subject: "Charged for plan I never upgraded to",
    body: "My account was automatically moved to the Pro tier without my consent. I want to be reverted to Free and refunded the $39.",
    fromName: "Amara Osei",
    fromEmail: "amara.osei@gmail.com",
    category: "RefundRequest",
    status: "Closed",
    daysAgo: 50,
  },
  {
    subject: "Software license key didn't work — want refund",
    body: "The license key I received (order #3341) throws an 'invalid key' error. I've tried 3 times. Please refund.",
    fromName: "Felix Wagner",
    fromEmail: "felix.w@gmx.de",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 12,
  },
  {
    subject: "Return window extended — requesting refund now",
    body: "I was told by support last month that my return window would be extended. I'd now like to proceed with the return and refund.",
    fromName: "Zara Ahmed",
    fromEmail: "zara.ahmed@hotmail.com",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 6,
  },
  {
    subject: "Refund for coupon that didn't apply at checkout",
    body: "I had a 20% coupon code but it didn't apply at checkout. I was charged full price. Please refund the discount amount.",
    fromName: "Henry Clark",
    fromEmail: "henry.clark@gmail.com",
    category: "RefundRequest",
    status: "Closed",
    daysAgo: 35,
  },

  // --- TechnicalQuestion ---
  {
    subject: "Cannot log in — password reset loop",
    body: "When I try to reset my password I receive the email but clicking the link just reloads the same page. Using Chrome on Windows 11.",
    fromName: "Grace Lee",
    fromEmail: "grace.lee@gmail.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 1,
  },
  {
    subject: "API returning 401 on valid token",
    body: "My API requests are returning 401 Unauthorized even though the JWT token is fresh (less than 5 minutes old). Endpoint: GET /api/v2/users.",
    fromName: "Sam Patel",
    fromEmail: "sam.patel@devcorp.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 3,
  },
  {
    subject: "Mobile app crashes on startup after update",
    body: "After updating to v3.4.1 on iOS 17, the app crashes immediately on launch. I've tried reinstalling but the same issue persists.",
    fromName: "Tiffany Morgan",
    fromEmail: "t.morgan@icloud.com",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 15,
  },
  {
    subject: "Webhook not firing on order completion",
    body: "Our webhook endpoint for the 'order.completed' event stopped receiving payloads 2 days ago. No changes made on our end. Endpoint verified working.",
    fromName: "Carlos Mendez",
    fromEmail: "carlos@ecomstoreapp.com",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 20,
  },
  {
    subject: "Two-factor authentication not sending SMS",
    body: "I enabled 2FA but never receive the SMS code. I've confirmed my phone number is correct (+1-555-0182). Please help.",
    fromName: "Nina Johansson",
    fromEmail: "nina.j@live.se",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 2,
  },
  {
    subject: "Data export producing empty CSV",
    body: "Every time I export my data to CSV the file downloads but contains only the header row. I have over 2,000 records. Tested in Firefox and Safari.",
    fromName: "Oliver Tan",
    fromEmail: "oliver.tan@gmail.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 4,
  },
  {
    subject: "SSO integration broken after domain change",
    body: "We changed our company domain last week. Now SSO via Okta fails with 'SAML assertion invalid'. Our IdP metadata has been updated.",
    fromName: "Rachel Kim",
    fromEmail: "rkim@bigenterprise.com",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 11,
  },
  {
    subject: "Bulk import fails on rows > 500",
    body: "CSV imports work fine up to 500 rows but fail silently after that. No error message shown. File size is well within the stated 10MB limit.",
    fromName: "Aaron Scott",
    fromEmail: "aaron.scott@datateam.io",
    category: "TechnicalQuestion",
    status: "Closed",
    daysAgo: 40,
  },
  {
    subject: "Notifications not appearing in app",
    body: "In-app notifications have stopped showing since last Tuesday. Browser notifications are enabled. I've cleared cache and tried a different browser.",
    fromName: "Lucia Reyes",
    fromEmail: "lucia.reyes@yahoo.es",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 17,
  },
  {
    subject: "Search results returning irrelevant items",
    body: "When I search for 'invoice' I get results about 'inventory'. The issue started after your search update last week.",
    fromName: "Patrick O'Connor",
    fromEmail: "p.oconnor@gmail.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 6,
  },
  {
    subject: "Dashboard charts not loading — blank white area",
    body: "The analytics charts on my dashboard are blank. Console shows: 'Error: Cannot read properties of undefined (reading map)'. Using Firefox 121.",
    fromName: "Yuki Tanaka",
    fromEmail: "yuki.tanaka@gmail.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 1,
  },
  {
    subject: "Zapier integration disconnecting every 24 hours",
    body: "Our Zap that connects your app to Google Sheets keeps disconnecting and requires manual reconnection every day. This started 10 days ago.",
    fromName: "Brittany Walsh",
    fromEmail: "brittany@automation.biz",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 22,
  },
  {
    subject: "File uploads stuck at 99% forever",
    body: "When uploading files over 20MB, the progress bar hits 99% and stays there indefinitely. Smaller files upload fine.",
    fromName: "Mohammed Al-Hassan",
    fromEmail: "m.alhassan@outlook.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 5,
  },
  {
    subject: "Emails going to spam — SPF/DKIM setup question",
    body: "Emails sent from your platform are landing in our clients' spam folders. Have you published SPF and DKIM records? Can you share the DNS entries we need to add?",
    fromName: "Sandra Eriksson",
    fromEmail: "sandra@marketingagency.se",
    category: "TechnicalQuestion",
    status: "Closed",
    daysAgo: 55,
  },
  {
    subject: "Report scheduling broken — emails not sent",
    body: "Scheduled reports are set to email every Monday morning but we haven't received one in 3 weeks. The schedule shows as 'active'.",
    fromName: "Tom Brennan",
    fromEmail: "tom.brennan@analytics.co",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 25,
  },
  {
    subject: "OAuth2 callback URL mismatch error",
    body: "Getting 'redirect_uri_mismatch' when trying to connect our app. We've registered https://app.oursite.com/callback in your developer portal.",
    fromName: "Kenji Watanabe",
    fromEmail: "kenji.w@devstudio.jp",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 2,
  },
  {
    subject: "Rate limit hit unexpectedly — need higher tier",
    body: "We're on the Business plan hitting the 1,000 req/min rate limit during peak hours. Our traffic analysis shows bursts of ~1,200 req/min. What are our options?",
    fromName: "Laura Müller",
    fromEmail: "laura.muller@b2bplatform.de",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 3,
  },
  {
    subject: "Table sorting broken in Safari",
    body: "Clicking column headers to sort works in Chrome and Firefox but has no effect in Safari 17.2 on macOS Sonoma.",
    fromName: "Jack Williams",
    fromEmail: "jack.w@designstudio.com",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 13,
  },
  {
    subject: "Print view layout is completely broken",
    body: "When printing invoices, the layout overflows and key fields are cut off on the right side. Issue occurs in both Chrome and Edge.",
    fromName: "Diane Foster",
    fromEmail: "diane.foster@accountingfirm.com",
    category: "TechnicalQuestion",
    status: "Closed",
    daysAgo: 65,
  },
  {
    subject: "Dark mode not saving preference",
    body: "I switch to dark mode but every time I refresh the page it reverts to light mode. I'm logged in and on the same device.",
    fromName: "Tyler Brooks",
    fromEmail: "tyler.b@gmail.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 1,
  },
  {
    subject: "Error 500 when saving custom fields",
    body: "Any time I try to save a new custom field on the contact form I get a 500 Internal Server Error. This has happened for 3 different field types.",
    fromName: "Ananya Krishnan",
    fromEmail: "ananya.k@crmusers.in",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 4,
  },

  // --- GeneralQuestion ---
  {
    subject: "What are your support hours?",
    body: "I couldn't find this on your website — what days and hours is live support available? Do you offer 24/7 coverage on any plan?",
    fromName: "Sarah Mitchell",
    fromEmail: "sarah.mitchell@gmail.com",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 70,
  },
  {
    subject: "How do I add a team member?",
    body: "I'm the account admin and want to invite a colleague. I can see a 'Team' section but the invite button is greyed out.",
    fromName: "Ben Larsson",
    fromEmail: "ben.larsson@startupco.io",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 16,
  },
  {
    subject: "Can I use my account on multiple devices?",
    body: "I work from both my laptop and desktop. Is there a limit on how many devices I can be signed in to simultaneously?",
    fromName: "Fatima Al-Rashid",
    fromEmail: "fatima.rashid@outlook.com",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 80,
  },
  {
    subject: "Is there a student discount available?",
    body: "I'm a university student and this tool would be really useful for my thesis project. Do you offer any academic or student pricing?",
    fromName: "Alex Torres",
    fromEmail: "a.torres@university.edu",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 28,
  },
  {
    subject: "How do I change my billing email?",
    body: "My invoices are being sent to my old email address. How do I update the billing email without changing my login email?",
    fromName: "Karen White",
    fromEmail: "karen.white@business.com",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 42,
  },
  {
    subject: "Do you offer a non-profit discount?",
    body: "We're a registered 501(c)(3) non-profit. Do you have special pricing or grants for non-profit organisations?",
    fromName: "Pastor James Okafor",
    fromEmail: "james@hopecharity.org",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 33,
  },
  {
    subject: "Where can I find my invoices?",
    body: "I need to download my invoices for our company accountant. I've looked under Settings but can't find them. Where are they?",
    fromName: "Chen Wei",
    fromEmail: "chen.wei@finance.com",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 55,
  },
  {
    subject: "Can I import data from a competitor?",
    body: "We're switching from a competitor and have all our data in their CSV export format. Do you support importing this, or is there a migration service?",
    fromName: "Ingrid Holm",
    fromEmail: "ingrid.holm@nordic.biz",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 21,
  },
  {
    subject: "How long are deleted records kept?",
    body: "If I delete a contact record, how long is it retained in your system before permanent deletion? We have compliance requirements.",
    fromName: "Bernard Dupont",
    fromEmail: "b.dupont@legalfirm.fr",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 48,
  },
  {
    subject: "What's the maximum file upload size?",
    body: "I'm trying to attach files to tickets but some of my files are large (50–200MB). What's the maximum size you support?",
    fromName: "Meera Nair",
    fromEmail: "meera.nair@mediahouse.com",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 19,
  },
  {
    subject: "Do you have a mobile app?",
    body: "I need to check on tickets while away from my desk. Is there an iOS/Android app, or is it mobile-browser only?",
    fromName: "Nathan Powell",
    fromEmail: "n.powell@gmail.com",
    category: "GeneralQuestion",
    status: "Open",
    daysAgo: 2,
  },
  {
    subject: "How do I cancel my account?",
    body: "We're shutting down our project and no longer need the service. How do I cancel the subscription and ensure my data is deleted?",
    fromName: "Claire Dubois",
    fromEmail: "claire.dubois@outlook.fr",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 24,
  },
  {
    subject: "What payment methods do you accept?",
    body: "I don't see PayPal listed as a payment option at checkout. Do you accept PayPal, or only credit/debit cards?",
    fromName: "Raj Gupta",
    fromEmail: "raj.gupta@freelancer.in",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 62,
  },
  {
    subject: "Is there a free plan?",
    body: "I'm evaluating tools for my small team (2 people). Is there a permanently free tier, or only a time-limited trial?",
    fromName: "Hannah Davis",
    fromEmail: "hannah.davis@gmail.com",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 37,
  },
  {
    subject: "Where is my data stored?",
    body: "We're in the EU and need to confirm GDPR compliance. Where are your servers located? Do you offer EU-only data residency?",
    fromName: "Marco Ricci",
    fromEmail: "marco.ricci@eu-company.it",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 75,
  },
  {
    subject: "Can I white-label the product?",
    body: "We want to resell your platform under our own brand. Do you offer white-label or OEM licensing?",
    fromName: "Stephanie Lang",
    fromEmail: "s.lang@resellerbiz.com",
    category: "GeneralQuestion",
    status: "Open",
    daysAgo: 3,
  },
  {
    subject: "How do I transfer ownership of my account?",
    body: "I'm leaving the company and need to transfer ownership to my colleague. How do I change the primary account holder?",
    fromName: "Derek Stone",
    fromEmail: "derek.stone@corp.com",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 26,
  },
  {
    subject: "Do you offer SLA guarantees?",
    body: "Our enterprise procurement team requires an SLA with at least 99.9% uptime. Do you offer this? Is there a formal SLA document?",
    fromName: "Lisa Park",
    fromEmail: "l.park@enterprise.co",
    category: "GeneralQuestion",
    status: "Open",
    daysAgo: 4,
  },
  {
    subject: "Can multiple admins manage the same account?",
    body: "We have 3 managers who all need admin access. Can each have their own login, or is there only one admin seat?",
    fromName: "Tobias Braun",
    fromEmail: "tobias.braun@mittelstand.de",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 58,
  },
  {
    subject: "Is there an affiliate or referral programme?",
    body: "I've recommended your product to several colleagues and they've signed up. Is there a referral programme where I could earn a discount?",
    fromName: "Fiona Campbell",
    fromEmail: "fiona.campbell@gmail.com",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 31,
  },

  // --- More TechnicalQuestion ---
  {
    subject: "PDF generation cuts off page 2 onward",
    body: "Exporting reports to PDF only includes page 1. Reports are typically 4–5 pages. This bug appeared after your update on the 3rd.",
    fromName: "Victor Espinoza",
    fromEmail: "v.espinoza@reportco.mx",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 23,
  },
  {
    subject: "Timezone offset causing wrong meeting times",
    body: "Meetings I schedule show correct time in my local timezone but appear 1 hour off for attendees in the same timezone. Daylight saving related?",
    fromName: "Alicia Green",
    fromEmail: "alicia.green@consulting.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 5,
  },
  {
    subject: "Custom domain pointing but SSL not provisioning",
    body: "I pointed my subdomain (help.mysite.com) 48 hours ago but SSL is still showing 'pending'. The DNS propagation looks correct.",
    fromName: "Sven Lindqvist",
    fromEmail: "sven@mysite.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 2,
  },
  {
    subject: "Magic link emails arriving 20+ minutes late",
    body: "Passwordless login magic links are arriving too late to be useful (they expire in 10 minutes). Our MX records look fine.",
    fromName: "Danielle Fox",
    fromEmail: "dfox@nonprofit.org",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 29,
  },
  {
    subject: "Can't delete account — button does nothing",
    body: "I go to Settings → Account → Delete Account, click the button, nothing happens. No confirmation dialog, no error. Chrome 121.",
    fromName: "George Thomas",
    fromEmail: "george.t@hotmail.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 7,
  },
  {
    subject: "Slack notification integration sends duplicate alerts",
    body: "Every event is being posted to our Slack channel twice simultaneously. We only have one webhook configured.",
    fromName: "Maria Santos",
    fromEmail: "maria.santos@techteam.com",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 18,
  },
  {
    subject: "Search returns no results after bulk import",
    body: "After importing 5,000 records via CSV yesterday, search returns nothing for any term. Records are visible in the list view.",
    fromName: "Chris Johansson",
    fromEmail: "chris.j@scandi.se",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 1,
  },
  {
    subject: "IP allowlist blocking valid company IPs",
    body: "We added our office IP range (192.168.10.0/24) to the allowlist but employees are still being blocked. Is CIDR notation supported?",
    fromName: "Natasha Ivanova",
    fromEmail: "n.ivanova@corp.ru",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 16,
  },
  {
    subject: "Infinite scroll not loading more items",
    body: "The ticket list infinite scrolls to ~50 items then stops loading. Scroll indicator shows but nothing loads. Network tab shows no new requests.",
    fromName: "Diego Herrera",
    fromEmail: "diego.h@latamco.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 3,
  },
  {
    subject: "Keyboard shortcuts stopped working",
    body: "The keyboard shortcuts (J/K for navigation, R for reply) stopped working after last week's update. Happens across all browsers.",
    fromName: "Amy Nguyen",
    fromEmail: "amy.nguyen@power-user.com",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 14,
  },

  // --- More RefundRequest ---
  {
    subject: "Charged for seat I removed a month ago",
    body: "I removed a user seat on June 1st but the July invoice still includes it. Please credit my account for the extra seat.",
    fromName: "Paul Kimura",
    fromEmail: "paul.kimura@saascompany.com",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 2,
  },
  {
    subject: "Bought wrong plan tier — refund difference",
    body: "I purchased the Enterprise plan instead of Business. Can you refund the $200 difference and downgrade my account?",
    fromName: "Wren Callahan",
    fromEmail: "wren.c@designfirm.com",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 9,
  },
  {
    subject: "App not supported on my OS — want refund",
    body: "Your system requirements page doesn't mention a macOS minimum version. The app doesn't run on my macOS 12.6 machine. I want a refund.",
    fromName: "Robert Nguyen",
    fromEmail: "robert.n@oldmac.com",
    category: "RefundRequest",
    status: "Closed",
    daysAgo: 36,
  },
  {
    subject: "Training session cancelled by your team",
    body: "Your team cancelled our booked training session (ref: TS-0091) with 30 minutes notice. I'd like a full refund of the $350 paid.",
    fromName: "Jenny Wu",
    fromEmail: "jenny.wu@bigcorp.com",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 11,
  },
  {
    subject: "Currency conversion charged extra",
    body: "I was charged in USD but my account is set to GBP. The exchange rate applied was significantly worse than market rate. Please refund the difference.",
    fromName: "Hugh Davies",
    fromEmail: "hugh.davies@uk.com",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 4,
  },

  // --- More GeneralQuestion ---
  {
    subject: "How do custom roles work?",
    body: "The docs mention 'custom roles' in the Enterprise tier. Can you explain what permissions can be customised and what can't?",
    fromName: "Valeria Rossi",
    fromEmail: "valeria.rossi@it.com",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 27,
  },
  {
    subject: "What happens to data if I downgrade?",
    body: "I'm considering downgrading from Business to Starter. Will I lose access to historical data, or just the features associated with Business?",
    fromName: "Craig Anderson",
    fromEmail: "craig.a@smallbiz.com",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 44,
  },
  {
    subject: "Do you have a status page?",
    body: "We experienced downtime last week and had no way to check if it was on our side or yours. Do you maintain a public status page?",
    fromName: "Hiroshi Yamamoto",
    fromEmail: "h.yamamoto@techco.jp",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 32,
  },
  {
    subject: "Can I lock down access by IP address?",
    body: "For security reasons, we want to restrict access to our account to only our office IP addresses. Is this possible on our current plan?",
    fromName: "Adaeze Obi",
    fromEmail: "adaeze.obi@securecorp.ng",
    category: "GeneralQuestion",
    status: "Open",
    daysAgo: 5,
  },
  {
    subject: "Where do I find API documentation?",
    body: "I'm a developer who wants to integrate your platform into our existing workflow. Where is the full API documentation? I only found a partial reference.",
    fromName: "Elias Svensson",
    fromEmail: "elias.dev@techstack.se",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 51,
  },
  {
    subject: "How do audit logs work?",
    body: "Our security team wants to review all admin actions. How long are audit logs retained, and can we export them?",
    fromName: "Patricia Evans",
    fromEmail: "p.evans@compliance.com",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 39,
  },

  // --- Mixed variety to hit 100 ---
  {
    subject: "Can't access account after company email domain change",
    body: "Our company changed its email domain. My old login email no longer exists. How do I regain access to my account?",
    fromName: "Jordan Blake",
    fromEmail: "jordan.blake@newdomain.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 1,
  },
  {
    subject: "Autopay failed — account suspended",
    body: "My card was updated but autopay failed and my account is suspended. I've added the new card — can you process the payment manually and reinstate?",
    fromName: "Susan Park",
    fromEmail: "susan.park@gmail.com",
    category: "GeneralQuestion",
    status: "Open",
    daysAgo: 2,
  },
  {
    subject: "Refund for early cancellation of annual plan",
    body: "I'm cancelling my annual plan 4 months early due to budget cuts. Per your policy, I believe I'm entitled to a pro-rated refund for unused months.",
    fromName: "Bruno Costa",
    fromEmail: "bruno.costa@ptcompany.pt",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 3,
  },
  {
    subject: "Email reply triggers duplicate ticket creation",
    body: "When a customer replies to a ticket email, a new ticket is created instead of adding to the thread. Threading is broken for all tickets.",
    fromName: "Helena Novak",
    fromEmail: "h.novak@helpdesk.cz",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 19,
  },
  {
    subject: "How do I set business hours for SLA timers?",
    body: "Our SLA timers run 24/7 but we only work Mon–Fri 9am–6pm. Where can I configure business hours so timers pause on nights and weekends?",
    fromName: "Ahmed Belkacem",
    fromEmail: "ahmed.b@support.dz",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 26,
  },
  {
    subject: "Transaction declined but I was still charged",
    body: "My payment was declined at checkout (I have the failure email) yet $79 still appears on my bank statement. Please investigate.",
    fromName: "Camille Lefort",
    fromEmail: "c.lefort@orange.fr",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 1,
  },
  {
    subject: "Username taken but that account appears inactive",
    body: "The username I want shows as taken but I can't find any public profile for it. Can you check if the account is active or release the username?",
    fromName: "Rhys Davies",
    fromEmail: "rhys.d@wales.uk",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 66,
  },
  {
    subject: "CSV import ignores custom field values",
    body: "Custom field columns in my import CSV are being ignored — after import, all records show empty custom fields. Headers match exactly.",
    fromName: "Femi Adeyemi",
    fromEmail: "femi.adeyemi@ng-tech.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 6,
  },
  {
    subject: "Can I pause my subscription instead of cancelling?",
    body: "I'm going on extended leave for 3 months. Can I pause billing rather than cancel and lose my data and settings?",
    fromName: "Isabelle Martin",
    fromEmail: "isabelle.martin@travelblog.fr",
    category: "GeneralQuestion",
    status: "Open",
    daysAgo: 2,
  },
  {
    subject: "Charged $0.00 repeatedly — possible billing bug",
    body: "I'm receiving payment confirmation emails for $0.00 every few hours. Nothing is being charged but it's generating confusion for our finance team.",
    fromName: "Stefan Müller",
    fromEmail: "stefan.mueller@finance.de",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 34,
  },
  {
    subject: "Add-on purchased but not reflected in account",
    body: "I bought the 'Advanced Analytics' add-on 2 hours ago (receipt attached). My account still shows I don't have it enabled.",
    fromName: "Pippa Hartley",
    fromEmail: "pippa.hartley@uk-startup.co.uk",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 1,
  },
  {
    subject: "How do I set up email forwarding to create tickets?",
    body: "I want support@mycompany.com to auto-create tickets here. What's the forwarding address and are there any SPF changes required?",
    fromName: "Arnav Shah",
    fromEmail: "arnav.shah@mycompany.in",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 22,
  },
  {
    subject: "Refund for workshop bundle — attended one session only",
    body: "I purchased a 5-session workshop bundle but can only attend 1. I'd like a refund for the 4 unused sessions ($240).",
    fromName: "Dominique Leblanc",
    fromEmail: "d.leblanc@education.ca",
    category: "RefundRequest",
    status: "Closed",
    daysAgo: 47,
  },
  {
    subject: "App uses excessive mobile data in background",
    body: "The mobile app is consuming ~2GB of background data per week with no settings open. This is draining my data plan rapidly.",
    fromName: "Lee Joon-ho",
    fromEmail: "leejh@mobile.kr",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 20,
  },
  {
    subject: "Forgot to apply coupon code — can you apply it now?",
    body: "I completed checkout without entering my coupon code SAVE30. Can you apply the 30% discount retroactively or issue a partial refund?",
    fromName: "Natalie Cooper",
    fromEmail: "natalie.c@gmail.com",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 8,
  },
  {
    subject: "Multi-language support — does it include Arabic?",
    body: "We serve customers across the Middle East. Does the UI support Arabic with right-to-left text direction, or is that on the roadmap?",
    fromName: "Khalid Al-Mansoori",
    fromEmail: "k.almansoori@me.ae",
    category: "GeneralQuestion",
    status: "Open",
    daysAgo: 4,
  },
  {
    subject: "Browser extension breaking login flow",
    body: "With my uBlock Origin extension active, the login button does nothing. Disabling it fixes the issue. Can you look into what's being blocked?",
    fromName: "Pieter De Vries",
    fromEmail: "pieter.dvries@nl.com",
    category: "TechnicalQuestion",
    status: "Closed",
    daysAgo: 53,
  },
  {
    subject: "Overcharged VAT — EU business exempt",
    body: "As an EU VAT-registered business I should be exempt from VAT charges. I was charged 20% VAT on my last 3 invoices. Please issue corrected invoices and refund.",
    fromName: "Anika Weber",
    fromEmail: "anika.weber@business.eu",
    category: "RefundRequest",
    status: "Open",
    daysAgo: 5,
  },
  {
    subject: "How do I merge duplicate contacts?",
    body: "I have many duplicate contact records from an old import. Is there a bulk merge tool, or do I have to merge them one by one?",
    fromName: "Tom Fletcher",
    fromEmail: "tom.fletcher@cleandata.com",
    category: "GeneralQuestion",
    status: "Resolved",
    daysAgo: 38,
  },
  {
    subject: "Password manager autofill not working",
    body: "My 1Password autofill does not recognise the login form fields. The fields have no standard name/id attributes that password managers use.",
    fromName: "Simone Ferrari",
    fromEmail: "simone.ferrari@gmail.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 2,
  },
  {
    subject: "Refund for subscription renewed during dispute",
    body: "My account was suspended during a billing dispute and renewed automatically while I couldn't access it. Please refund the renewal charge of $59.",
    fromName: "Monica Okonkwo",
    fromEmail: "monica.o@ng.com",
    category: "RefundRequest",
    status: "Resolved",
    daysAgo: 15,
  },
  {
    subject: "Activity feed showing events from wrong team",
    body: "My activity feed shows events from a different team's workspace. I'm only a member of the 'Marketing' workspace. Serious privacy concern.",
    fromName: "Garrett Mills",
    fromEmail: "g.mills@bigorg.com",
    category: "TechnicalQuestion",
    status: "Resolved",
    daysAgo: 43,
  },
  {
    subject: "What is your data breach notification policy?",
    body: "For our security review, we need to understand your breach notification timeline and process. Is this documented anywhere?",
    fromName: "Dr. Anna Fischer",
    fromEmail: "a.fischer@sicherheit.de",
    category: "GeneralQuestion",
    status: "Closed",
    daysAgo: 72,
  },
  {
    subject: "Wrong currency on invoices after region change",
    body: "I moved my account region to UK but invoices still show USD. All settings display GBP but the invoices are wrong.",
    fromName: "Callum Reid",
    fromEmail: "callum.reid@gmail.com",
    category: "TechnicalQuestion",
    status: "Open",
    daysAgo: 3,
  },
];

async function main() {
  const agents = await db.user.findMany({ where: { role: "agent" } });

  const now = new Date();

  const data = TICKETS.map((t, i) => {
    const createdAt = new Date(now);
    createdAt.setDate(createdAt.getDate() - t.daysAgo);
    // Stagger hours so tickets on the same day have different timestamps
    createdAt.setHours((i * 3) % 24, (i * 7) % 60, 0, 0);

    // Assign roughly half the tickets to agents (cycling through available agents)
    const assignedTo =
      agents.length > 0 && i % 2 === 0
        ? agents[i % agents.length].id
        : undefined;

    return {
      subject: t.subject,
      body: t.body,
      fromName: t.fromName,
      fromEmail: t.fromEmail,
      category: t.category,
      status: t.status,
      createdAt,
      updatedAt: createdAt,
      assignedTo,
    };
  });

  const result = await db.ticket.createMany({ data });
  console.log(`Created ${result.count} tickets.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
